language: python
python:
  - "3.5"
# command to install dependencies
before install:
  - sudo apt-get -qq update
  - sudo apt-get install -y samtools
  - echo "$PATH"
  - echo "which samtools"
 
install: 
   - pip3.5 install coveralls
   - pip3.5 install -r requirements.txt
# running script
script: 
   - ./install_samtools.sh 
   - ./debug_travis.sh 
   - python3.5 setup.py install
   - python3.5 tests/utils3_5_tests.py -s /home/travis/bin/samtools
   - coverage tests/utils3_5_tests.py
#   - nosetests --with-coverage # Add me to run nose with coverage support.
after_success:
  coveralls
