language: python
python:
- '3.5'
- '3.6'
before install:
- sudo apt-get -qq update
- sudo apt-get install -y samtools
- echo "$PATH"
- echo "which samtools"
install:
- pip install coveralls
- pip install -r requirements.txt
script:
- "./install_samtools.sh"
- "./debug_travis.sh"
- python setup.py install
- nosetests --with-coverage --cover-package=pyutilsnrw tests/
after_success: coveralls
deploy:
  provider: pypi
 #server: https://mypackageindex.com/index
  user: NickWaters
  password: itsablunderfullife
  on:
    tags: true
